" VIM Konfigurationsdatei
" vim: fileformat=unix  filetype=vim foldmethod=marker :



" Misc {{{1

lang C

" https://github.com/tpope/vim-pathogen
call pathogen#infect()

set paste

syntax on
set tabpagemax=50

" tabs as spaces
set expandtab

filetype plugin indent on

set ignorecase

" Trailing Whitespaces als "~" darstellen.
" see here: http://vim.wikia.com/wiki/Highlight_unwanted_spaces
set list listchars=trail:~
set nolist


" Die Kommandozeile kommt mit dem Sonderzeichen nicht klar
if has("gui_running")
   " Tabs als »··
   " borks under Linux gtkvim
   set list listchars+=tab:»
endif

" Includes {{{1

" MAC-OS spezifische Einstellungen
source  <sfile>:h/include/macos.vimrc

" Mutt
" source  <sfile>:h/include/mutt.vimrc

" Statuszeile
source  <sfile>:h/include/statusline.vimrc

" Diverses
source  <sfile>:h/include/misc.vimrc

" Rechtschreibkorrektur
source  <sfile>:h/include/spelling.vimrc

" golang
source  <sfile>:h/include/golang.vimrc

" git syntax
autocmd BufNewFile,BufRead COMMIT_EDITMSG set filetype=gitcommit

source  <sfile>:h/include/tabtooltip.vimrc

" Modeline {{{1

" http://unix.stackexchange.com/questions/19875/setting-vim-filetype-with-modeline-not-working-as-expected
set modeline
set modelines=2

" Tagbar/NERDTree {{{1
" https://github.com/majutsushi/tagbar
nmap <F8> :TagbarToggle<CR>
nmap <F9> :NERDTreeToggle<CR>

" Color Scheme ----------------------------------------------------------- {{{1

" Set the color scheme.
try
    colorscheme solarized
    set background=dark
catch /E185:/
    colorscheme desert256
endtry


" Solarized -------------------------------------------------------------- {{{2

if exists('g:colors_name') && g:colors_name == 'solarized'
    " Text is unreadable with background transparency.
    if has('gui_macvim')
        set transparency=0
    endif

    " Highlighted text is unreadable in Terminal.app because it
    " does not support setting of the cursor foreground color.
    if !has('gui_running') && ($TERM_PROGRAM == 'Apple_Terminal' || $TERM == 'xterm-256color' || $TERM == 'xterm-color' || $TERM == 'xterm')
        let g:solarized_termcolors = &t_Co
        let g:solarized_termtrans = 1
        colorscheme solarized
    endif
endif

highlight CursorLine  cterm=NONE ctermbg=black guibg=black
